Minmax agent
gartangh/Deep-Learning-Project pull request #6
Opened 2020-04-04 19:13 UTC by aimjy

added the logic of minimax agent with alpha beta pruning
-> but can be slow...

In future may add limit of iterations/seconds before forcing to return?

2020-04-04 20:10 UTC, gartangh requested changes

2020-04-04 20:10 UTC, gartangh commented on othello/game_logic/agents/minimax_agent.py
> +				if cur_best_score is None or cur_best_score < points:
int is compared with NoneType in case black and white have no legal moves.

2020-04-04 22:48 UTC, aimjy commented
Issue about finishing game into simulation should be fixed!

2020-04-05 00:39 UTC, gartangh approved these changes

2020-04-05 00:39 UTC, merged